language: node_js

node_js:
  - "lts/*"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update

script:
  - yarn test
  - yarn build

after_script: greenkeeper-lockfile-upload

cache:
  yarn: true
  directories:
    - "node_modules"